# https://www.machinelearningplus.com/101-numpy-exercises-python/

In [98]:
# 1
import numpy as np
print(np.__version__)

1.13.1


In [5]:
# 2
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# 3
print(np.full(shape = (3, 3), fill_value= True, dtype = bool))
# print(np.ones((3, 3), dtype = bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
# 4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [17]:
# 5
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [21]:
# 6
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# new_arr = np.copy(arr)
# new_arr[arr % 2 == 1] = -1
new_arr = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(new_arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [22]:
# 7
arr = np.arange(10)
print(arr.reshape(2, 5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
# 8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.vstack((a, b)))
# print(np.concatenate((a, b), axis = 0))
# print(np.r_[a, b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [36]:
# 9
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.hstack((a, b)))
# print(np.concatenate((a, b), axis = 1))
# print(np.c_[a, b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [41]:
# 10
a = np.array([1,2,3])
print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [45]:
# 11
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


In [46]:
# 12
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a, b))

[1 2 3 4]


In [53]:
# 13
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.arange(a.shape[0])[a == b])
print(np.where(a == b))

[1 3 5 7]
(array([1, 3, 5, 7]),)


In [61]:
# 14
a = np.arange(15)
# index = np.where((a >= 5) & (a <= 10))
# print(a[index])
print(a[(a >= 5) & (a <= 10)])

[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [66]:
# 15
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
pair_max = np.vectorize(maxx, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
print(pair_max(a, b))

[ 6.  7.  9.  8.  9.  7.  5.]


In [70]:
# 16
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, (0, 2, 1)])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [71]:
# 17
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[(0, 2, 1), :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [6 7 8]
 [3 4 5]]


In [76]:
# 18
arr = np.arange(9).reshape(3,3)
print(arr)
# print(arr[(2, 1, 0), :])
print(arr[::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [80]:
# 19
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, ::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [82]:
# 20
print(np.random.uniform(low=5.0, high=10.0, size=(5, 3)))

[[ 7.42281144  6.6011107   9.70849283]
 [ 9.78950138  9.51085409  9.14392295]
 [ 6.15950093  6.17428312  7.16161536]
 [ 5.1524318   6.66129564  8.01936326]
 [ 5.12383542  6.27281014  9.79885912]]


In [83]:
# 21
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
print(rand_arr)

[[ 0.317  0.212  0.945]
 [ 0.405  0.855  0.9  ]
 [ 0.805  0.089  0.287]
 [ 0.382  0.959  0.285]
 [ 0.487  0.301  0.512]]


In [89]:
# 22
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[ 0.000543  0.000278  0.000425]
 [ 0.000845  0.000005  0.000122]
 [ 0.000671  0.000826  0.000137]]


In [90]:
# 23
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ..., 12 13 14]


In [95]:
# 24
np.set_printoptions(threshold=np.nan)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [99]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
a = np.genfromtxt(url, delimiter=',', dtype=object)
print(a[2])

[b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
