# https://www.machinelearningplus.com/101-numpy-exercises-python/
reference: https://docs.scipy.org/doc/numpy-1.13.0/genindex.html

In [2]:
# 1
import numpy as np
print(np.__version__)

1.13.1


In [5]:
# 2
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# 3
print(np.full(shape = (3, 3), fill_value= True, dtype = bool))
# print(np.ones((3, 3), dtype = bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
# 4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [17]:
# 5
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [21]:
# 6
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# new_arr = np.copy(arr)
# new_arr[arr % 2 == 1] = -1
new_arr = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(new_arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [22]:
# 7
arr = np.arange(10)
print(arr.reshape(2, 5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
# 8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.vstack((a, b)))
# print(np.concatenate((a, b), axis = 0))
# print(np.r_[a, b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [36]:
# 9
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.hstack((a, b)))
# print(np.concatenate((a, b), axis = 1))
# print(np.c_[a, b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [41]:
# 10
a = np.array([1,2,3])
print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [45]:
# 11
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


In [46]:
# 12
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a, b))

[1 2 3 4]


In [53]:
# 13
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.arange(a.shape[0])[a == b])
print(np.where(a == b))

[1 3 5 7]
(array([1, 3, 5, 7]),)


In [61]:
# 14
a = np.arange(15)
# index = np.where((a >= 5) & (a <= 10))
# print(a[index])
print(a[(a >= 5) & (a <= 10)])

[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [66]:
# 15
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
pair_max = np.vectorize(maxx, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
print(pair_max(a, b))

[ 6.  7.  9.  8.  9.  7.  5.]


In [70]:
# 16
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, (0, 2, 1)])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [71]:
# 17
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[(0, 2, 1), :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [6 7 8]
 [3 4 5]]


In [76]:
# 18
arr = np.arange(9).reshape(3,3)
print(arr)
# print(arr[(2, 1, 0), :])
print(arr[::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [80]:
# 19
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, ::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [82]:
# 20
print(np.random.uniform(low=5.0, high=10.0, size=(5, 3)))

[[ 7.42281144  6.6011107   9.70849283]
 [ 9.78950138  9.51085409  9.14392295]
 [ 6.15950093  6.17428312  7.16161536]
 [ 5.1524318   6.66129564  8.01936326]
 [ 5.12383542  6.27281014  9.79885912]]


In [83]:
# 21
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
print(rand_arr)

[[ 0.317  0.212  0.945]
 [ 0.405  0.855  0.9  ]
 [ 0.805  0.089  0.287]
 [ 0.382  0.959  0.285]
 [ 0.487  0.301  0.512]]


In [89]:
# 22
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[ 0.000543  0.000278  0.000425]
 [ 0.000845  0.000005  0.000122]
 [ 0.000671  0.000826  0.000137]]


In [90]:
# 23
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ..., 12 13 14]


In [126]:
print(x.shape, y.shape, x.dtype, y.dtype)

(2, 256, 256, 3) (2, 256, 256, 1) float32 float64


In [95]:
# 24
np.set_printoptions(threshold=np.nan)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [116]:
# 25
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
a = np.genfromtxt(url, delimiter=',', dtype=object)
print(a[2])

[b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']


In [119]:
# 26
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)
species = np.array([row[4] for row in iris_1d])
species[:5]

(150,)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'],
      dtype='|S18')

In [152]:
# 27
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_2d = np.array([row.tolist() for row in iris_1d])
print(iris_2d[1])

[b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']


In [163]:
# 28
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=float, usecols=(0))
mean, med, std = np.mean(iris), np.median(iris), np.std(iris)
print(mean, med, std)

5.84333333333 5.8 0.825301291785


In [180]:
# 29
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
ma = np.max(iris)
mi = np.min(iris)
shift_scale = (sepallength - mi) / (ma - mi)
# shift_scale = (sepallength - mi) / sepallength.ptp()
shift_scale[:10]

array([ 0.222222,  0.166667,  0.111111,  0.083333,  0.194444,  0.305556,
        0.083333,  0.194444,  0.027778,  0.166667])

In [191]:
# 30
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
def softmax(x):
    ma = np.max(x)
    e_x = np.exp(x - ma) # original formula is: e_x = np.exp(x), optimize for computation stability
    su = np.sum(e_x)
    return e_x / su
print(softmax(sepallength))

[ 0.00222   0.001817  0.001488  0.001346  0.002008  0.002996  0.001346
  0.002008  0.001102  0.001817  0.002996  0.001644  0.001644  0.000997
  0.00447   0.004044  0.002996  0.00222   0.004044  0.00222   0.002996
  0.00222   0.001346  0.00222   0.001644  0.002008  0.002008  0.002453
  0.002453  0.001488  0.001644  0.002996  0.002453  0.003311  0.001817
  0.002008  0.003311  0.001817  0.001102  0.00222   0.002008  0.001218
  0.001102  0.002008  0.00222   0.001644  0.00222   0.001346  0.002711
  0.002008  0.01484   0.008144  0.013428  0.003311  0.009001  0.004044
  0.007369  0.001817  0.009947  0.002453  0.002008  0.00494   0.005459
  0.006033  0.003659  0.010994  0.003659  0.00447   0.006668  0.003659
  0.00494   0.006033  0.007369  0.006033  0.008144  0.009947  0.01215
  0.010994  0.005459  0.004044  0.003311  0.003311  0.00447   0.005459
  0.002996  0.005459  0.010994  0.007369  0.003659  0.003311  0.003311
  0.006033  0.00447   0.002008  0.003659  0.004044  0.004044  0.006668
  0.002

In [194]:
# 31
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength, (5, 95))

array([ 4.6  ,  7.255])

In [195]:
# 32
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Method 1
i, j = np.where(iris_2d)

# i, j contain the row numbers and column numbers of 600 elements of iris_x
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan

# Method 2
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [212]:
# 33
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:, 0])
res = np.isnan(iris_2d[:, 0])
print("the missing value is at {}".format(np.where(res)))
print("the number of missing value is {}".format(np.sum(res)))

[ 5.1  4.9  4.7  4.6  5.   5.4  4.6  5.   4.4  4.9  5.4  4.8  4.8  4.3  5.8
  5.7  5.4  5.1  5.7  5.1  5.4  5.1  4.6  5.1  4.8  5.   5.   5.2  5.2  4.7
  4.8  5.4  5.2  5.5  4.9  5.   5.5  nan  4.4  5.1  5.   4.5  4.4  5.   5.1
  4.8  5.1  4.6  5.3  5.   7.   6.4  6.9  5.5  6.5  5.7  6.3  4.9  6.6  5.2
  5.   5.9  6.   6.1  5.6  6.7  5.6  5.8  6.2  5.6  5.9  6.1  6.3  6.1  6.4
  6.6  6.8  6.7  6.   5.7  5.5  5.5  5.8  6.   5.4  6.   6.7  6.3  5.6  5.5
  5.5  6.1  5.8  5.   5.6  5.7  5.7  6.2  5.1  5.7  6.3  5.8  7.1  6.3  6.5
  7.6  4.9  7.3  6.7  7.2  6.5  6.4  6.8  5.7  5.8  6.4  6.5  7.7  7.7  6.
  6.9  5.6  7.7  6.3  6.7  7.2  6.2  6.1  nan  7.2  7.4  7.9  nan  6.3  6.1
  7.7  6.3  6.4  6.   6.9  6.7  6.9  5.8  6.8  6.7  6.7  6.3  6.5  6.2  5.9]
the missing value is at (array([ 37, 128, 132]),)
the number of missing value is 3


In [220]:
# 34
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
index = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[index]

array([[ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4.8,  3.1,  1.6,  0.2],
       [ 4.9,  2.4,  3.3,  1. ],
       [ 4.9,  2.5,  4.5,  1.7]])

In [238]:
# 35
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
res = iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0]
# Solution 2
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
res = iris_2d[any_nan_in_row]

(133, 4)

In [434]:
# 36
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])[0, 1]

0.87175415730487182

In [449]:
# 37
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[3,2] = np.nan
np.any(np.isnan(iris_2d))
# np.isnan(iris_2d).any()

True

In [450]:
# 38
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.isnan(iris_2d)] = 0

In [461]:
# 39
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
np.unique(iris[:, 4], return_counts=True, return_index=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'], dtype=object),
 array([  0,  50, 100]),
 array([50, 50, 50]))

In [492]:
# 40
# solution1
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
petallength = iris[:, 2]
out = np.where(petallength.astype(float) < 3, "small", np.where(petallength.astype(float) < 5, "medium", "large") )
print(out[48: 53])
# solution2
# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])
# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]
# View
print(petal_length_cat[48: 53])

['small' 'small' 'medium' 'medium' 'medium']
['small', 'small', 'medium', 'medium', 'medium']


In [510]:
# 41
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3
# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]
# Add the new column
out = np.hstack([iris_2d, volume])
# View
out[2:5, 5]

array([30.0723720777127, 33.238050274980004, 36.65191429188092], dtype=object)

In [1]:
# numpy.linalg.svd
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.svd.html

In [37]:
# 42
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
species_arr = np.unique(iris[:, -1])
print(species_arr)
np.random.seed(100)
print(np.random.choice(species_arr, 5, p=[0.5, 0.25, 0.25]))

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']
[b'Iris-versicolor' b'Iris-setosa' b'Iris-setosa' b'Iris-virginica'
 b'Iris-setosa']


In [54]:
# 43
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
np.sort(np.unique(iris[iris[:, 4] == b'Iris-setosa'][:, 2]))[-2]

b'1.7'

In [89]:
# 44
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
# solution 1
names = [('sepallength', 'object'), ('sepalwidth', 'object')
         , ('petallength', 'object'), ('petalwidth', 'object'), ('species', 'object')]
iris_tuple = np.array([tuple(x) for x in iris.tolist()], dtype=names)
sortted_iris = np.sort(iris_tuple, order='sepallength')
np.set_printoptions(threshold = 10)
print("--------solution1-----------")
print(sortted_iris)
# solution 2, better!
print("---------solution2----------")
print(iris[np.argsort(iris[:, 0])])

--------solution1-----------
[(b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa')
 (b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa')
 (b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa') ...,
 (b'7.7', b'3.0', b'6.1', b'2.3', b'Iris-virginica')
 (b'7.7', b'3.8', b'6.7', b'2.2', b'Iris-virginica')
 (b'7.9', b'3.8', b'6.4', b'2.0', b'Iris-virginica')]
---------solution2----------
[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 ..., 
 [b'7.7' b'3.8' b'6.7' b'2.2' b'Iris-virginica']
 [b'7.7' b'3.0' b'6.1' b'2.3' b'Iris-virginica']
 [b'7.9' b'3.8' b'6.4' b'2.0' b'Iris-virginica']]


In [95]:
# 45
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
value_arr, count_arr = np.unique(iris[:, 2], return_counts=True)
print("most frequency value is {}".format(value_arr[np.argmax(count_arr)]))

most frequency value is b'1.5'


In [8]:
# 46
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
# solution 1
print("the first element greater than 1.0 in the 4th column in dataset is {}"
      .format(np.argwhere(iris[:, 3].astype(float) > 1.0)[0]))
# solution 2
print(np.argmax(iris[:, 3].astype('float') > 1.0))

the first element greater than 1.0 in the 4th column in dataset is [50]
50


In [16]:
# 47
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
# solution 1
a = np.where(a > 30, 30, np.where(a < 10, 10, a))
print(a)
# solution 2
# print(np.clip(a, a_min=10, a_max=30))

[ 27.62684215  14.64009987  21.80136195  42.39403048   1.23122395
   6.95688692  33.86670515  41.466785     7.69862289  29.17957314
  44.67477576  11.25090398  10.08108276   6.31046763  11.76517714
  48.95256545  40.77247431   9.42510962  40.99501269  14.42961361]
[ 27.62684215  14.64009987  21.80136195  30.          10.          10.          30.
  30.          10.          29.17957314  30.          11.25090398
  10.08108276  10.          11.76517714  30.          30.          10.          30.
  14.42961361]


In [23]:
# 48
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
# solution 1
print(a[np.argsort(a)[-5:]])
# solution 2
print(np.sort(a)[-5:])
# solution 3
print(np.partition(a, kth=-5)[-5:])

[ 27.62684215  14.64009987  21.80136195  42.39403048   1.23122395
   6.95688692  33.86670515  41.466785     7.69862289  29.17957314
  44.67477576  11.25090398  10.08108276   6.31046763  11.76517714
  48.95256545  40.77247431   9.42510962  40.99501269  14.42961361]
[ 40.99501269  41.466785    42.39403048  44.67477576  48.95256545]
[ 40.99501269  41.466785    42.39403048  44.67477576  48.95256545]
[ 40.99501269  41.466785    42.39403048  44.67477576  48.95256545]


In [27]:
# 49

In [44]:
# 50
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
print(array_of_arrays.shape)
arr_2d = np.array([a for arr in array_of_arrays for a in arr])
print(arr_2d.shape)

(3,)
(10,)


In [59]:
# 51
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
print(arr)
row_count = arr.shape[0]
column_count = np.unique(arr).shape[0]
onehot_arr = np.zeros((row_count, column_count))
# solution 1
onehot_arr[np.arange(row_count), arr - 1] = 1
print("one-hot encoding as \n{}".format(onehot_arr))
# solution 2
for i, k in enumerate(arr):
    onehot_arr[i, k-1] = 1
# solution 3, the most elegant solution
print((arr[:, None] == np.unique(arr)).view(np.int8))

[2 3 2 2 2 1]
one-hot encoding as 
[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]]
[[0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


In [78]:
# 52
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
print(species_small)
[i for val in np.unique(species_small) for i, grp in enumerate(species_small[ species_small == val])]

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']


[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]

In [80]:
# 53

In [105]:
# 54
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
# solution 1
out = np.full_like(a, -1)
for i, val in enumerate(np.argsort(a)):
    out[val] = i 
print(out)
# solution 2
print(a.argsort().argsort())

[ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]
[4 2 6 0 8 7 9 3 5 1]


In [96]:
# 55
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [107]:
# 55
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

a_shape = a.shape
a_flatten = a.reshape(-1)
# also: 
# a.flatten()
# a.ravel()

out = a_flatten.argsort().argsort()
out = out.reshape(a_shape)
print(out)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


In [111]:
# 56
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
print("maximun value in each row as {}".format(np.argmax(a, axis = 1)))

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
maximun value in each row as [0 0 2 0 2]


In [123]:
# 57
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
# solution 1
max_arr = a[np.arange(a.shape[0]), np.argmax(a, axis=1)]
min_arr = a[np.arange(a.shape[0]), np.argmin(a, axis=1)]
print("max-by-min for each row as {}".format(min_arr / max_arr))
# solution 2
print(np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1))

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
max-by-min for each row as [ 0.44444444  0.125       0.5         1.          0.11111111]
[ 0.44444444  0.125       0.5         1.          0.11111111]


In [127]:
# 58
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print(a)
## Solution
# There is no direct function to do this as of 1.13.3

# Create an all True array
out = np.full(a.shape[0], True)

# Find the index positions of unique elements
unique_positions = np.unique(a, return_index=True)[1]

# Mark those positions as False
out[unique_positions] = False

print(out)
#> [False  True False  True False False  True  True  True  True]

[0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]


In [139]:
# 59
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# No direct way to implement this. Just a version of a workaround.
numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

# List comprehension version
[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]

# For Loop version
output = []
for group_val in np.unique(grouping_column):
    output.append([group_val, numeric_column[grouping_column==group_val].mean()])
print(output)

[[b'Iris-setosa', 3.4180000000000001], [b'Iris-versicolor', 2.7700000000000005], [b'Iris-virginica', 2.9740000000000002]]


In [141]:
# 60
from io import BytesIO
from PIL import Image
import PIL, requests

# Import image from URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# Read it as Image
I = Image.open(BytesIO(response.content))

# Optionally resize
I = I.resize([150,150])

# Convert to numpy array
arr = np.asarray(I)

# Optionaly Convert it back to an image and show
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

In [155]:
# 61
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a)
print(a[~np.isnan(a)])

[  1.   2.   3.  nan   5.   6.   7.  nan]
[ 1.  2.  3.  5.  6.  7.]


In [160]:
# 62
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
# solution 1
print(np.sqrt(np.sum((a - b) ** 2)))
# solution 2, better
print(np.linalg.norm(a-b))

6.7082039325
6.7082039325


In [162]:
# 63
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5])

In [165]:
# 64
# Input
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

# Solution
print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [170]:
# 65
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.where(x == 1)[0][4]

8

In [179]:
# 66
dt64 = np.datetime64('2018-02-25 22:10:10')

# Solution
from datetime import datetime
print(type(dt64.tolist()))

# or

print(type(dt64.astype(datetime)))

<class 'datetime.datetime'>
<class 'datetime.datetime'>


In [183]:
# 67
np.random.seed(100)
Z = np.random.randint(10, size=10)
print(Z)
np.convolve(Z, np.ones(3)/3, mode='valid')

[8 8 3 7 7 0 4 2 5 2]


array([ 6.33333333,  6.        ,  5.66666667,  4.66666667,  3.66666667,
        2.        ,  3.66666667,  3.        ])

In [198]:
# 68
# Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers
np.arange(10) * 3 + 5

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [199]:
# 69

In [200]:
# 70