# https://www.machinelearningplus.com/101-numpy-exercises-python/

In [98]:
# 1
import numpy as np
print(np.__version__)

1.13.1


In [5]:
# 2
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# 3
print(np.full(shape = (3, 3), fill_value= True, dtype = bool))
# print(np.ones((3, 3), dtype = bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
# 4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [17]:
# 5
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [21]:
# 6
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# new_arr = np.copy(arr)
# new_arr[arr % 2 == 1] = -1
new_arr = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(new_arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [22]:
# 7
arr = np.arange(10)
print(arr.reshape(2, 5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
# 8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.vstack((a, b)))
# print(np.concatenate((a, b), axis = 0))
# print(np.r_[a, b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [36]:
# 9
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.hstack((a, b)))
# print(np.concatenate((a, b), axis = 1))
# print(np.c_[a, b])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [41]:
# 10
a = np.array([1,2,3])
print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [45]:
# 11
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))

[2 4]


In [46]:
# 12
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a, b))

[1 2 3 4]


In [53]:
# 13
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.arange(a.shape[0])[a == b])
print(np.where(a == b))

[1 3 5 7]
(array([1, 3, 5, 7]),)


In [61]:
# 14
a = np.arange(15)
# index = np.where((a >= 5) & (a <= 10))
# print(a[index])
print(a[(a >= 5) & (a <= 10)])

[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [66]:
# 15
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
pair_max = np.vectorize(maxx, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
print(pair_max(a, b))

[ 6.  7.  9.  8.  9.  7.  5.]


In [70]:
# 16
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, (0, 2, 1)])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [71]:
# 17
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[(0, 2, 1), :])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [6 7 8]
 [3 4 5]]


In [76]:
# 18
arr = np.arange(9).reshape(3,3)
print(arr)
# print(arr[(2, 1, 0), :])
print(arr[::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [80]:
# 19
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, ::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [82]:
# 20
print(np.random.uniform(low=5.0, high=10.0, size=(5, 3)))

[[ 7.42281144  6.6011107   9.70849283]
 [ 9.78950138  9.51085409  9.14392295]
 [ 6.15950093  6.17428312  7.16161536]
 [ 5.1524318   6.66129564  8.01936326]
 [ 5.12383542  6.27281014  9.79885912]]


In [83]:
# 21
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
print(rand_arr)

[[ 0.317  0.212  0.945]
 [ 0.405  0.855  0.9  ]
 [ 0.805  0.089  0.287]
 [ 0.382  0.959  0.285]
 [ 0.487  0.301  0.512]]


In [89]:
# 22
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[ 0.000543  0.000278  0.000425]
 [ 0.000845  0.000005  0.000122]
 [ 0.000671  0.000826  0.000137]]


In [90]:
# 23
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ..., 12 13 14]


In [95]:
# 24
np.set_printoptions(threshold=np.nan)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [116]:
# 25
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
a = np.genfromtxt(url, delimiter=',', dtype=object)
print(a[2])

[b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']


In [119]:
# 26
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)
species = np.array([row[4] for row in iris_1d])
species[:5]

(150,)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'],
      dtype='|S18')

In [152]:
# 27
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_2d = np.array([row.tolist() for row in iris_1d])
print(iris_2d[1])

[b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']


In [163]:
# 28
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype=float, usecols=(0))
mean, med, std = np.mean(iris), np.median(iris), np.std(iris)
print(mean, med, std)

5.84333333333 5.8 0.825301291785


In [180]:
# 29
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
ma = np.max(iris)
mi = np.min(iris)
shift_scale = (sepallength - mi) / (ma - mi)
# shift_scale = (sepallength - mi) / sepallength.ptp()
shift_scale[:10]

array([ 0.222222,  0.166667,  0.111111,  0.083333,  0.194444,  0.305556,
        0.083333,  0.194444,  0.027778,  0.166667])

In [191]:
# 30
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
def softmax(x):
    ma = np.max(x)
    e_x = np.exp(x - ma) # original formula is: e_x = np.exp(x), optimize for computation stability
    su = np.sum(e_x)
    return e_x / su
print(softmax(sepallength))

[ 0.00222   0.001817  0.001488  0.001346  0.002008  0.002996  0.001346
  0.002008  0.001102  0.001817  0.002996  0.001644  0.001644  0.000997
  0.00447   0.004044  0.002996  0.00222   0.004044  0.00222   0.002996
  0.00222   0.001346  0.00222   0.001644  0.002008  0.002008  0.002453
  0.002453  0.001488  0.001644  0.002996  0.002453  0.003311  0.001817
  0.002008  0.003311  0.001817  0.001102  0.00222   0.002008  0.001218
  0.001102  0.002008  0.00222   0.001644  0.00222   0.001346  0.002711
  0.002008  0.01484   0.008144  0.013428  0.003311  0.009001  0.004044
  0.007369  0.001817  0.009947  0.002453  0.002008  0.00494   0.005459
  0.006033  0.003659  0.010994  0.003659  0.00447   0.006668  0.003659
  0.00494   0.006033  0.007369  0.006033  0.008144  0.009947  0.01215
  0.010994  0.005459  0.004044  0.003311  0.003311  0.00447   0.005459
  0.002996  0.005459  0.010994  0.007369  0.003659  0.003311  0.003311
  0.006033  0.00447   0.002008  0.003659  0.004044  0.004044  0.006668
  0.002

In [194]:
# 31
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength, (5, 95))

array([ 4.6  ,  7.255])

In [195]:
# 32
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Method 1
i, j = np.where(iris_2d)

# i, j contain the row numbers and column numbers of 600 elements of iris_x
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan

# Method 2
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [212]:
# 33
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:, 0])
res = np.isnan(iris_2d[:, 0])
print("the missing value is at {}".format(np.where(res)))
print("the number of missing value is {}".format(np.sum(res)))

[ 5.1  4.9  4.7  4.6  5.   5.4  4.6  5.   4.4  4.9  5.4  4.8  4.8  4.3  5.8
  5.7  5.4  5.1  5.7  5.1  5.4  5.1  4.6  5.1  4.8  5.   5.   5.2  5.2  4.7
  4.8  5.4  5.2  5.5  4.9  5.   5.5  nan  4.4  5.1  5.   4.5  4.4  5.   5.1
  4.8  5.1  4.6  5.3  5.   7.   6.4  6.9  5.5  6.5  5.7  6.3  4.9  6.6  5.2
  5.   5.9  6.   6.1  5.6  6.7  5.6  5.8  6.2  5.6  5.9  6.1  6.3  6.1  6.4
  6.6  6.8  6.7  6.   5.7  5.5  5.5  5.8  6.   5.4  6.   6.7  6.3  5.6  5.5
  5.5  6.1  5.8  5.   5.6  5.7  5.7  6.2  5.1  5.7  6.3  5.8  7.1  6.3  6.5
  7.6  4.9  7.3  6.7  7.2  6.5  6.4  6.8  5.7  5.8  6.4  6.5  7.7  7.7  6.
  6.9  5.6  7.7  6.3  6.7  7.2  6.2  6.1  nan  7.2  7.4  7.9  nan  6.3  6.1
  7.7  6.3  6.4  6.   6.9  6.7  6.9  5.8  6.8  6.7  6.7  6.3  6.5  6.2  5.9]
the missing value is at (array([ 37, 128, 132]),)
the number of missing value is 3


In [220]:
# 34
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
index = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[index]

array([[ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4.8,  3.1,  1.6,  0.2],
       [ 4.9,  2.4,  3.3,  1. ],
       [ 4.9,  2.5,  4.5,  1.7]])

In [238]:
# 35
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
res = iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0]
# Solution 2
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
res = iris_2d[any_nan_in_row]

(133, 4)

In [434]:
# 36
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])[0, 1]

0.87175415730487182

In [449]:
# 37
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[3,2] = np.nan
np.any(np.isnan(iris_2d))
# np.isnan(iris_2d).any()

True

In [450]:
# 38
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d[np.isnan(iris_2d)] = 0

In [461]:
# 39
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
np.unique(iris[:, 4], return_counts=True, return_index=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'], dtype=object),
 array([  0,  50, 100]),
 array([50, 50, 50]))

In [492]:
# 40
# solution1
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
petallength = iris[:, 2]
out = np.where(petallength.astype(float) < 3, "small", np.where(petallength.astype(float) < 5, "medium", "large") )
print(out[48: 53])
# solution2
# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])
# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]
# View
print(petal_length_cat[48: 53])

['small' 'small' 'medium' 'medium' 'medium']
['small', 'small', 'medium', 'medium', 'medium']


In [510]:
# 41
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
# names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3
# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]
# Add the new column
out = np.hstack([iris_2d, volume])
# View
out[2:5, 5]

array([30.0723720777127, 33.238050274980004, 36.65191429188092], dtype=object)